// Placeholder types. In a real build these would be generated by `ts-rs`
// from the Rust structs in `crates/core/src/model.rs`. Keep the shapes in
// sync with the Rust side.

export type ServiceId = "youdao" | "deepl" | "google" | "bing" | "openai";

export interface ServiceConfig {
  id: ServiceId;
  enabled: boolean;
  priority: number;
  options: Record<string, unknown>;
}

export interface GeneralConfig {
  target_language: string;
  default_from: string;
  theme: "light" | "dark" | "system";
}

export interface Config {
  version: number;
  general: GeneralConfig;
  shortcut: string;
  services: Record<string, ServiceConfig>;
  hotkey_registration_failed?: boolean;
}

export interface TranslateResult {
  service_id: ServiceId;
  service_name: string;
  text: string;
  detected_source: string | null;
  elapsed_ms: number;
  extra?: Record<string, unknown>;
}

export interface ServiceErrorDto {
  code: string;
  message: string;
}

export interface ServiceOutcomeDto {
  service_id: ServiceId;
  service_name: string;
  result: TranslateResult | null;
  error: ServiceErrorDto | null;
}
