// Placeholder types. In a real build these would be generated by `ts-rs`
// from the Rust structs in `crates/core/src/model.rs`. Keep the shapes in
// sync with the Rust side.

export type ServiceId = "youdao" | "deepl" | "google" | "bing" | "openai";
export type AppLanguageCode =
  | "system"
  | "en"
  | "zh-Hans"
  | "zh-Hant"
  | "ja"
  | "ko"
  | "fr"
  | "de"
  | "es"
  | "ru"
  | "pt"
  | "it"
  | "ar";

export interface ServiceConfig {
  id: ServiceId;
  enabled: boolean;
  priority: number;
  options: Record<string, unknown>;
}

export interface GeneralConfig {
  target_language: string;
  default_from: string;
  preferred_languages: string[];
  theme: "light" | "dark" | "system";
  app_language: AppLanguageCode;
  auto_copy: boolean;
  auto_translate_clipboard_on_hotkey: boolean;
  proxy: ProxyConfig;
}

export interface AppConfig {
  show_menu_bar_icon: boolean;
  launch_at_startup: boolean;
}

export interface ProxyConfig {
  enabled: boolean;
  url: string;
}

export interface WindowConfig {
  always_on_top: boolean;
  display_position: "remember" | "right" | "center" | "mouse" | string;
  last_position?: WindowPosition | null;
}

export interface WindowPosition {
  x: number;
  y: number;
}

export interface UpdateConfig {
  check_on_startup: boolean;
  allow_beta: boolean;
}

export interface HistoryItem {
  id: string;
  source_text: string;
  translated_text: string;
  service_id: string;
  service_name: string;
  from: string;
  to: string;
  created_at_ms: number;
}

export interface Config {
  version: number;
  general: GeneralConfig;
  app: AppConfig;
  shortcut: string;
  services: Record<string, ServiceConfig>;
  history: HistoryItem[];
  window: WindowConfig;
  updates: UpdateConfig;
  hotkey_registration_failed?: boolean;
}

export interface TranslateResult {
  service_id: ServiceId;
  service_name: string;
  from: string | null;
  to: string;
  text: string;
  audio_url?: string | null;
  detected_source: string | null;
  elapsed_ms: number;
  dictionary?: DictionaryResult | null;
  source_dictionary?: DictionaryResult | null;
  target_dictionary?: DictionaryResult | null;
  extra?: Record<string, unknown>;
}

export interface DictionaryResult {
  phonetics?: WordPhonetic[];
  parts?: DictionaryPart[];
  exchanges?: WordExchange[];
  simple_words?: SimpleDictionaryWord[];
  tags?: string[];
}

export interface WordPhonetic {
  label: string;
  value?: string | null;
  audio_url?: string | null;
  accent?: string | null;
}

export interface DictionaryPart {
  part?: string | null;
  means: string[];
}

export interface WordExchange {
  name: string;
  words: string[];
}

export interface SimpleDictionaryWord {
  word: string;
  part?: string | null;
  means?: string[];
}

export interface ServiceErrorDto {
  code: string;
  message: string;
}

export interface ServiceOutcomeDto {
  service_id: ServiceId;
  service_name: string;
  result: TranslateResult | null;
  error: ServiceErrorDto | null;
}

export interface TranslationStartedDto {
  request_id: string;
  outcomes: ServiceOutcomeDto[];
}

export interface TranslationOutcomeDto {
  request_id: string;
  outcome: ServiceOutcomeDto;
}

export interface TranslationFinishedDto {
  request_id: string;
}

export interface HotkeySourceDto {
  text: string | null;
  error: string | null;
  source: "selection" | "clipboard" | "none" | string;
}

export interface UpdateInfoDto {
  available: boolean;
  version: string | null;
  current_version: string;
  channel: string;
  date: string | null;
  body: string | null;
}

export type UpdateStatus =
  | "idle"
  | "checking"
  | "up-to-date"
  | "available"
  | "installing"
  | "installed"
  | "failed";

export interface UpdateStatusDto {
  status: UpdateStatus | string;
  update: UpdateInfoDto | null;
  error: string | null;
  downloaded: number | null;
  total: number | null;
}
